lowRISC/sonata-system

- data/pins_sonata.xdc
- doc/guide/getting-started.md
- rtl/fpga/clkgen_sonata.sv
- rtl/fpga/top_sonata.sv
- sonata.core
This commit assumes revision 0.2 of the board. It adds a pin file, a top level module, a clock generator and the appropriate changes to the core file. It also updates the getting started guide to use the Sonata PCB by default.
This commit is derived from a PR in the demo system: https://github.com/lowRISC/ibex-demo-system/pull/86
> Add support for Sonata PCB

- doc/guide/getting-started.md
- dv/verilator/sonata_verilator_lint.vlt
- rtl/system/sonata_system.sv
- sonata_system.core
- vendor/lowrisc_ibex/ibex_top_tracing.core
- vendor/lowrisc_ibex/rtl/ibexc_top_tracing.sv
- vendor/patches/lowrisc_ibex/0006-Tracing.patch
Note to use tracing one needs to add ` --verilator_options='+define+RVFI'` to the build command, e.g.
```sh
fusesoc --cores-root=. \
run --target=sim --tool=verilator --setup \
--build lowrisc:sonata:system \
--verilator_options='+define+RVFI'
```
> Add tracing support to the sonata system

- vendor/lowrisc_ip.lock.hjson
- vendor/lowrisc_ip/ip/uart/rtl/uart.sv
- vendor/lowrisc_ip/ip/uart/rtl/uart_reg_top.sv
- vendor/lowrisc_ip/util/reggen/ip_block.py
- vendor/patches/lowrisc_ip/uart/0002-Remove-Integrity-Check.patch
This was accidentally added back in when I upgraded the primitives. This integrity check is causing bus errors.
> Remove UART integrity

- dv/verilator/sonata_system_main.cc
- flake.nix
- rtl/system/sonata_system.sv
- rtl/system/sram.sv
- sonata_system.core
The address out from tlul_adapter_sram has already the last two bit trimmed. We further strip out the bits before feeding it to the cap ram, causes multiple words to be mapped to the same address in the cap ram.
I move the SRAM related part to a dedicated module so logically related parts are grouped together.
> Fix capability tag corruption of SRAM

- dv/verilator/top_verilator.sv
- rtl/fpga/top_sonata.sv
- rtl/system/sonata_system.sv
CHERI shall be enabled by default. To disable CHERI functionality experimentally, eg. to run the legacy code base, set DIP switch 8 to ON before bringing the system out of reset.
If wishing to toggle a FPGA image with downloaded code between CHERI and non-CHERI, the Reset switch on the Sonata board may be used, provided that the software has not destructively modified RAM contents eg. code.
> Introduce CHERI enable/disable switch

- rtl/system/rv_timer.sv
- sw/legacy/common/timer.h
- sw/legacy/timer_test/timer_test.cc
Transpose mtime and mtimecmp registers in rv_timer implementation to match CLINT specification.
Change legacy software accordingly.
> Fix rv_timer register offsets

- rtl/system/sonata_system.sv
- rtl/system/sram.sv
Originally the clock on the B port of the capability tags were connected to the reset instead of the clock. This PR fixes that. It also fixes some width warnings that Vivado produces.
> SRAM tag fix

- data/xbar_main.hjson
- dv/verilator/top_verilator.sv
- rtl/bus/tl_main_pkg.sv
- rtl/fpga/top_sonata.sv
- rtl/system/sonata_system.sv
- rtl/system/sram.sv
- sw/cheri/tests/revocation_test.cc
- sw/cheri/tests/spi_test.cc
- sw/cheri/tests/uart_check.cc
- sw/legacy/common/sonata_system.h
- sw/legacy/demo/hello_world/main.c
- sw/legacy/link.ld
- sw/legacy/test/memory_test.c
- Increase SRAM size to 256KiB by avoiding bit-level write enables.
- Increase system clock frequency to 30MHz (just misses timing at 33MHz presently).
- Resurrect legacy 'hello_word' demo application now that rv_timer is usable.
This build is timing clean on A50T and passes legacy code tests (memory_test, i2c_hat_id, hello_world, hello_usb) and hello_compartment from the CHERIoT RTOS world.
> 256KiB RAM, 30MHz system clock on A50T

- rtl/system/sonata_system.sv
- rtl/system/sram.sv
- sw/cheri/tests/CMakeLists.txt
- sw/cheri/tests/tag_test.S
There is a single capability tag bit per 64 bits of data. With two bits per 64 bits a write to one half of the 64-bit capability will not invalidate the capability tag associated with the other half.
> Shrink tag RAM

- .github/workflows/ci.yml
These actions should help keep the legacy software and simulator in a buildable state.
You can see both of them passing here: https://github.com/marnovandermaas/sonata-system/actions
> Basic actions

- data/pins_sonata.xdc
- rtl/fpga/top_sonata.sv
- sw/legacy/demo/i2c_hat_id/i2c_hat_id.c
This PR adds support for the other I2C buses on the Sonata board.
- I2C0 drives qwiic0, RPi HAT ID and Arduino.
- I2C1 drives qwiic1, RPi GPIO/I2C bus and mikroBUS Click.
The `i2c_hat_id` demo application is modified to read and report the SparkFun AS6212 Temperature Sensor reading as well as the IMU 'WHO_AM_I' registers from the other I2C bus on the RPi Sense HAT.
This is therefore reading from I2C1 (IMU) as well as two separate devices on the I2C0 bus. I2C devices are presently not available on mikroBUS Click and Arduino boards for testing.
> Add support for other I2C buses

- rtl/fpga/top_sonata.sv
Removing a debug feature from the main branch.
> Hardwire CHERI to enable

- SUMMARY.md
- doc/architecture/board.md
- doc/dev/fpga-development.md
- doc/guide/building-examples.md
- doc/guide/fpga-update.md
- doc/guide/toolchain-setup.md
Update based on new instructions as well as removing features that are not yet supported.
Fixes: https://github.com/lowRISC/sonata-system/issues/91
> Doc updates

- .github/workflows/ci.yml
- dv/verilator/sonata_system.cc
- dv/verilator/sonata_verilator_lint.vlt
- flake.nix
- sonata.core
- sw/cheri/sim_boot_stub/Makefile
- sw/cheri/sim_boot_stub/README.md
- sw/cheri/sim_boot_stub/boot.S
- sw/cheri/sim_boot_stub/link.ld
I'd like this working for the hackathon so if you've got more major changes you'd like following review I'd appreciate it if we could just record it in an issue for now and get this merged.
> Verilator v5

- .github/workflows/ci.yml
This doesn't push to the cache but it should allow it use our CI machine's local nix store so would speed up the simulator build by quite a bit.
> Run simulator on custom nix runner

- doc/guide/building-examples.md
In the documentation we should just recommend that people use cmake to pull in the correct version of the SDK.
> Resolve documentation pointing to wrong SDK

- rtl/ip/rgbled_ctrl/rtl/rgbled_ctrl.sv
It's been observed that the existing LED clearing on power up was not sufficient as the LEDs were turning on on FPGA reset.
This adds a time deley before we first clear the LEDs as well as a repeated clear to ensure it takes effect.
Additionally some comments have been added to the existing RTL.
> [rtl] More thorough LED clearing on power up

- rtl/system/jtag_id_pkg.sv
- util/sonata-openocd-cfg.tcl
This is according to lowRISC's part number registry: https://github.com/lowRISC/part-number-registry/blob/main/jtag_partno.md
> Use Sonata JTAG IDCODE instead of demo system

- sw/cheri/error_leds/error.S
Programs need to be 4 byte aligned for srec to happliy convert them to vmem files. The `.trap` section wasn't in the linker script, which meant the ALIGN function in the linker script wasn't of any use.
Too see build error make this change on current main (https://github.com/lowRISC/sonata-system/commit/e7c62e713caccd17e169804da4f9009d6ada7d42).
```diff
diff --git a/sw/cheri/error_leds/error.S b/sw/cheri/error_leds/error.S
index b6967bb..36e9e20 100644
--- a/sw/cheri/error_leds/error.S
+++ b/sw/cheri/error_leds/error.S
@@ -123,7 +123,7 @@ accesssystemregister:
.section .text.trap, "ax", @progbits
.p2align 2
trap:
-       li t0, 0x01000000 //0x10 for simulation 0x01000000 for FPGA.
+       li t0, 0x00000010 //0x10 for simulation 0x01000000 for FPGA.
delayloop: // Delay clearing error LEDs …
```
> Fixed alignment problem in error_leds program

- rtl/system/pwm_fade.sv
- rtl/system/sonata_system.sv
- sonata_system.core
This is done with a new `pwm_fade` block, placed between the error signal from the core and the led output.
> Fade capability LEDs when switching off

- sw/cheri/boot/boot.S
`cjr cra` requires `cra` to be a return sentry in newer version of CHERIoT Ibex. Use `ct0` instead to avoid this problem.
Based on this commit:
https://github.com/CHERIoT-Platform/cheriot-safe-uart-boot-rom/commit/82fbc153075b2532b124a9eb1c223d1e61666e3b
Fixes: https://github.com/lowRISC/sonata-system/issues/134
> Fix bootloader to avoid return sentry

- rtl/system/sonata_system.sv
After creating https://github.com/lowRISC/sonata-system/issues/137 , realised the comments wouldn't take long to fix, so fixed them.
*Vim's <kbd>Ctrl</kbd>+<kbd>A</kbd> is a god send I reach for a surprising amount.*
> Fixed interrupt indices

- doc/guide/building-examples.md
- dv/verilator/top_verilator.sv
- sw/cheri/boot/boot_loader.cc
- sw/cheri/tests/spi_test.cc
- sw/common/defs.h
- sw/legacy/common/uart.c
The motivation for changing this is to speed up the CHERIoT RTOS test suite that spends a lot of time waiting for UART.
Changing to 921,600 from 115,200 decreased the runtime from 20 to 6 minutes.
I chose 921,600 because it is the closest standard baud rate to the maximum possible baud rate of 937,500.[^1] This is very close the the maximum, but the error (0.55 cycles) hasn't caused problems in simulation or on FPGA.
[^1]: The UART divides the clock by 16 (for over sampling on the receive side) and then by 2, so the maximum baud rate is the clock divided by 32. The clock is currently 30,000,000 so the maximum baud rate is 937,500. The closest standard baud rate below this is 921,600.
> Increased the default baud rate

- sw/cheri/boot/boot_loader.cc
- sw/cheri/common/flash-utils.hh
- sw/cheri/common/timer-utils.hh
If the system is reset while a SPI access is going on, the SPI device might not be in the correct state and using it directly will fail, and we don't show helpful message in this case, just "Failed ELF Magic Check".
Add a software reset sequence to reset it to a well known state before accessing.
> Reset SPI flash before accessing it

- rtl/ip/hyperram/rtl/hbmc_tl_top.sv
Two changes made:
* HyperRAM controller tag RAM's cmd and wdata FIFO get merged into one. There's only 1 bit for the data so there isn't much need to separate cmd and data FIFO.
* Initialise `ufifo_rd_ena` in the beginning of `always_comb` block to zero. Otherwise Vivado will infer it as a latch.
> HyperRAM fix and improvements

- README.md
- doc/guide/building-examples.md
- doc/guide/fpga-update.md
- doc/guide/rp2040-update.md
Updated the docs linked from getting started to match what's needed for the v0.3 release, note the downgrade on the baud rate (things built with sonata-software are still running on 115200).
I'd appreciate a rapid review on this, the prior v0.2 release was effectively broken because the latest main of sonata-software wouldn't build binaries compatible with it (due to the switch to writing .elf directly to flash). We've got a new (working) v0.3 release done but want to ensure people reading the getting started docs are guided appropriately so they can use it.
There's more doc updates/reviews to do to get everything consistent for v1.0 this is just the critical stuff so the getting started material is consistent with the latest working release.
> [doc] Update getting started docs for latest release

- util/sonata-openocd-cfg.tcl
The set_prefer_sba command has been deprecated, set_mem_access should be used instead.
> [util] Fix sonata-openocd-cfg.tcl for use with OpenOCD 0.12.0

- vendor/lowrisc_ibex.lock.hjson
- vendor/lowrisc_ibex/rtl/ibexc_top.sv
Update code from upstream repository
https://github.com/lowrisc/cheriot-ibex.git to revision b4209e3aaf64061869e0ab8b9616efc151fca4f5
* [rtl] Fix ICache scramble key valid input (Greg Chadwick)
> Update lowrisc_ibex to lowrisc/cheriot-ibex@b4209e3a

- README.md
Now the getting started guide lives in a 'README.md' we cannot link the README.md directly as it will work on github but not in the rendered mdbook. Instead link to the directory containing the getting started guide.
On github this still takes you to a page with the rendered documentationm just with a directory listing on top of it. Crucially it fixes the rendered mdbook version.
> [doc] Fix getting started link in top-level README

- sw/cheri/boot/boot.S
- sw/cheri/checks/cheri_sanity.cc
- sw/cheri/common/boot.S
- sw/cheri/link.ld
Fix linker script and boot.S so globals can be used without tag violations.
> Fix global variables support

- rtl/system/sonata_system.sv
Connect the interrupt lines from the USBDEV IP block to the PLIC.
Note: None of the SPI controllers yet has its interrupt lines wired up either, but there's no driving logic either at present, and the number of controllers may well change.
> Connect USBDEV interrupts to the PLIC

- sw/cheri/common/flash-utils.hh
- sw/cheri/tests/spi_tests.hh
- sw/cheri/tests/test_runner.cc
This PR adds a SPI test to the existing baremetal CHERI test runner. For now, this is a simple smoketest that simply tests a few commands for the SPI flash - other SPI connections are not included.
The SPI tests consist of 3 components:
1. Read the JEDEC ID from flash over SPI and check it matches the value we expect.
2. Erase 1 random sector (4 KiB) from flash over SPI, and check that the entire sector was properly erased.
3. Write 10 random pages (256 B) to flash over SPI, and then read back the data to check that it matches what was written.
The number of test iterations and the number of sectors and pages can each be configured via compilation flags. These numbers are purposefully kept fairly low to keep runtime reasonable on Verilator.
This commit also includes minor changes to the …
> Add SPI test for CHERI

- dv/dpi/i2cdpi/i2c_as621x.cc
- dv/dpi/i2cdpi/i2c_as621x.hh
- dv/dpi/i2cdpi/i2c_hat_id.cc
- dv/dpi/i2cdpi/i2c_hat_id.hh
- dv/dpi/i2cdpi/i2c_lsm9ds1.cc
- dv/dpi/i2cdpi/i2c_lsm9ds1.hh
- dv/dpi/i2cdpi/i2cdevice.cc
- dv/dpi/i2cdpi/i2cdevice.hh
- dv/dpi/i2cdpi/i2cdpi.cc
- dv/dpi/i2cdpi/i2cdpi.hh
- dv/dpi/i2cdpi/i2cdpi.sv
- dv/verilator/top_verilator.sv
- sonata.core
- sw/legacy/demo/i2c_hat_id/i2c_hat_id.c
Introduce a generic DPI model of an I2C bus with an arbitrary number of attached I2C devices. All bus speeds and device behaviours including Sr (restart) conditions should be supported, and only support for clock stretching and multiple controllers is presently unimplemented. Out-Of-Band signals are present in each direction for future extensions such as interrupt signalling.
Introduce simple device models for:
-  RPi Sense HAT ID EEPROM
- RPi Sense HAT IMU (`WHO_AM_I` registers only)
- AS621x Digital Temperature Sensor
These are the devices that are presently anticipated and exercised by the `sw/legacy/demo/i2c_hat_id` code, allowing the code to produce the same results in Verilator simulation as on the FPGA build.
> Implement I2C DPI and device models

- flake.lock
`lowrisc-nix`'s u2fconv doesn't propagate inputs so `python3` is now the correct version.
> Updated to latest lowrisc-nix version

- rtl/fpga/top_sonata.sv
In `top_sonata.sv`, the `clk_i` and `rst_ni` signals were not actually connected to the main system clock and reset signals. This PR hooks them up so that pinmux can actually be used on FPGA.
> Hook up system clock to pinmux

- dv/verilator/top_verilator.sv
- rtl/system/sonata_system.sv
`mhpmcounter_get` is verilator specific, so should live in top_verilator.
> Moved verilator specific function out of sonata_system

- flake.nix
- sw/cheri/CMakeLists.txt
See commits for more detailed explanations.
This PR re-adds testing of the CHERIoT RTOS test suite in our test suite, such that it will now also run in CI where appropriate. To make the test suite work, the CHERIoT RTOS source used in `flake.nix` has been bumped to point to the [`hyperram` branch](https://github.com/lowRISC/cheriot-rtos/tree/hyperram), instead of `main`. To keep these in sync, the corresponding git tag in the relevant CMake build file is also updated. With these changes, the test suite should now once again pass as expected. 
It also doubles the time available for regular tests to run in simulation in CI, because we're getting quite close to the timeout on longer variations after adding the SPI, I2C and hyperram tests, and it already times out locally on my machine.
Not …
> Re-add CHERIoT RTOS test suite to Nix testing infrastructure.

- dv/verilator/sonata_system.cc
This fixes the problem of `mhpmcounter_get` not being in scope.
> Changed verilator's scope to top_verilator

- doc/ip/pwm.md
There has been a significant divergence between the RTL and the documentation.
Update the documentation to match the RTL to avoid changing the (working) design at this point.
> Update PWM documentation to match RTL

- data/pins_sonata.xdc
- data/synth_timing.xdc
- sonata.core
- util/sonata-openocd-cfg.tcl
- Add I/O timing constraints for all ports.
- Correct FPGA speed-grade to the faster "-2" grade.
- Increase openocd JTAG speed using on-board programmer (used when loading programs into SRAM from computer).
- Add missing HyperRAM physical IOB constraint.
- Tidy pins_sonata.xdc and update deprecated properties.
The biggest change (by volume) is by far the I/O timing constraints. These should improve timing on some synchronous interfaces, such as the User JTAG, and improve reliability.
Further changes/refinements are likely.
Note that internal timing constraints have yet to be tackled.
Also note that build times may increase slightly due the there being more for the tool to consider and optimise timing-wise.
> Add I/O timing cons, fix speed-grade, faster JTAG

- rtl/system/debounce_step.sv
- rtl/system/gpio.sv
- sonata_system.core
Use a shared debounce counter for all pins, rather than a counter each.
> Rework GPIO debounce to save area

- data/synth_timing.xdc
Sole remaining timing failure is a setup timing path from the td_i port. Fix it by relaxing hold timing, which appeared to be the root cause of the setup timing issue.
We can justify  this relaxing of the hold timing constraint by assuming that the driver of the input is launching the data on falling clock edges as they are supposed to.
> Relax td_i/tms_i hold requirement

- sw/cheri/common/console-utils.hh
- sw/cheri/tests/plic_tests.hh
- sw/cheri/tests/uart_tests.hh
Ensure that `intr_test` for Status-type interrupts is cleared after using it within `PlicTest`, because otherwise subsequent tests may fail.
Helps `test_runner` run multiple times without an intervening system-global reset, and better supports test reordering.
> Improve robustness of test_runner

- data/xbar_main.hjson
- data/xbar_main_generated.hjson
- rtl/bus/xbar_main.sv
- rtl/system/sonata_system.sv
Use the xbar_main fabric to introduce a tlul_fifo_sync between the debug host port and the RAM, and lose the manual instantiation from sonata_system.
This should produce no functional change, it's just a tidy up. Tested on FPGA (timing clean and functional) and no UNOPTFLAT issues with Verilator.
> Tidy debug access to RAM

- flake.nix
- sw/cheri/CMakeLists.txt
This will bring sonata-software and sonata-system in line with each other to use the same CHERIoT-RTOS commit (at the time I make this PR)
> Bump CHERIoT RTOS version

- sw/cheri/error_leds/error.S
This removes PermitStoreLocalCap from error LEDs since this is no longer supported in CHERIoT Ibex. It also make the cycling on FPGA go faster which is a nicer effect.
> Error LEDs fixed

- .github/workflows/ci.yml
This avoids the need to login in GCP.
The FPGA job on this PR used the cached bitstream.
I also changed an RTL file to check that it would build the bitstream.
> [ci, fpga] Download the cached bitstream using the public link

- .github/workflows/ci.yml
Only upload bitstreams to the cache when it is built.
> [ci, fpga] Avoid unnecessary bitstream upload

- flow/vivado_hook_opt_design_post.tcl
- flow/vivado_hook_opt_design_pre.tcl
- flow/vivado_hook_route_design_post.tcl
- flow/vivado_hook_route_design_pre.tcl
- flow/vivado_setup.tcl
- sonata.core
Add flow hooks to implement some optional timing optimisations:
- Add timing margin to clk_sys for early implementation stages. This allows faster clk_sys speeds w/o much additional runtime.
- Add optional additional logic optimisation.
- Add two levels of post-route optimisation commands. This allows even faster clk_sys speeds at the cost of added runtime.
All these optimisations are controlled by an `opt` TCL variable set in the hook that is first called in the implementation flow.
> Add phys-based timing optimisations

- data/pins_sonata.xdc
- data/top_config.toml
- doc/ip/gpio.md
- doc/ip/pinmux.md
- dv/verilator/top_verilator.sv
- rtl/fpga/top_sonata.sv
- rtl/system/pinmux.sv
- rtl/system/sonata_pkg.sv
Wire up the on-board MicroSD card slot to an existing SPI controller via pinmux.
CS line is connected at top-level.
Card detection is connected to fixed GPI.
As-yet untested.
> Connect MicroSD card slot to an SPI controller

- nix/software.nix
- sw/cheri/CMakeLists.txt
- sw/cheri/tests/i2c_tests.hh
- sw/cheri/tests/plic_tests.hh
More detailed info in the commit messages.
See [here](https://github.com/lowRISC/cheriot-rtos/compare/34fc63bd6f11ba747b2e98e49f40eb5949809682...lowRISC:cheriot-rtos:c29bdeccc0335b81acea09c069fc94ca044a5a14) for the change in the CHERIoT RTOS source being used, which only contains commits from https://github.com/lowRISC/cheriot-rtos/pull/16.
This PR simply updates the CHERIoT RTOS source, and then makes small changes to the PLIC and I2C tests so that they continue working in the same way with the driver updates. The driver updates that need to be handled are the change of the `Nack` I2C interrupt to a `ControllerHalt` interrupt, and that the `blocking_write` function now returns a result that must be appropriately checked. 
This functionality is blocking the Pinmux test and check …
> Update CHERIoT RTOS source and tests to use updated I2C driver

- nix/tests.nix
- rtl/ip/spi/data/spi.hjson
- rtl/ip/spi/rtl/spi.sv
- rtl/ip/spi/rtl/spi_core.sv
- rtl/ip/spi/rtl/spi_reg_pkg.sv
- rtl/ip/spi/rtl/spi_reg_top.sv
- sw/cheri/common/sonata-devices.hh
- sw/cheri/tests/spi_tests.hh
This PR consists of three commits:
1. An implementation of a loopback test using an external jumper wire on the RPi header (P19-P20) which could be installed in CI, although this is proof-of-concept and we probably want to use one of the other SPI connections since the RPi header is probably in use.
2. Implement an internal loopback mode in the SPI controller, to permit testing of all controllers in all modes (CPOL, CPHA, MSB_FIRST) and a software reset mechanism if - say - a command is started but not completed, and a block reset has not been/cannot be performed.
3. Test all of the SPI controllers using internal loopback, and all modes.
This has all been tested on FPGA; I suggest that once there's agreement on the physical practicalities w.r.t. CI we should enable a loopback test on a …
> SPI loopback, software reset and associated testing

- nix/software.nix
- sw/cheri/CMakeLists.txt
This version dependencies of the stl headers.
> [log] Bump fmt lib to v0.2.2

- sw/cheri/common/platform-pinmux.hh
This PR updates the Pinmux driver so that it is no longer out of date with the most recent pinmux changes that introduce the MicroSD card (see #239). This involves adding two more output pin registers for the MicroSD clock & command pins, and allowing the Spi3 Receive to have 1 more value selected (i.e. the MicroSD Dat0). Specifically see the changes to `pinmux.md` in 8c8d34961891770537a4af93767d8b3ab7448b45 to understand why the changes in this PR have been made.
> Add MicroSD pins to Pinmux Driver

- sw/cheri/tests/plic_tests.hh
- util/test_runner.py
Present logging information about the IP-level interrupt state, since this is more useful in the event of a failure.
Extend the IP-level interrupt state testing for SPI and USBDEV since this was incomplete.
> Expand both checking and logging of IRQs

- nix/software.nix
- sw/cheri/CMakeLists.txt
Adds more STL header dependencies that are still missing.
> Bump fmt library version again

- dv/verilator/top_verilator.sv
- nix/software.nix
- rtl/fpga/top_sonata.sv
- sw/cheri/CMakeLists.txt
- sw/cheri/checks/revocation_test.cc
- sw/common/defs.h
- sw/legacy/common/sonata_system.h
Increase `clk_sys` from 30 MHz to 40 MHz. Includes some physical-design-like tweaks to the Vivado flow to achieve timing closure at 40 MHz or possibly beyond.
See individual commit messages for further details.
> 40 MHz Core clock

- dv/dpi/i2cdpi/i2cdpi.cc
- dv/dpi/i2cdpi/i2cdpi.hh
- dv/verilator/top_verilator.sv
The two DPI models did not model the post-pinmux changes to the I2C buses; there are no longer just two physical I2C buses electrically commoned within the FPGA.
Separate the I2C devices into three I2C DPI models representing the physical buses that have devices at present. Tie the other I2C buses inactive, modelling the pullups on the FPGA board.
Modify `i2cdpi` so that it properly handles traffic to an address at which there is no connected device.
> Update Verilator top level and I2C DPI models to match Sonata board

- sw/cheri/tests/i2c_tests.hh
- sw/cheri/tests/pinmux_tests.hh
Prevent a low GPIO input to the UART Rx input causing the test to run indefinitely without timeout. A low Rx input keeps the UART RX logic active and prevents it becoming Idle except for infrequent single-cycle assertions of Idle.
Also switch the output driver before redirecting the input for more predictable behaviour.
Use higher I2C speed when reading the RPi HAT ID EEPROM to reduce the test duration substantially.
Reduce the timeout values in the UART and GPIO testing to more practical values for FPGA and reduce the simulation time.
> Recover from low Rx input. Reduce test duration by shortening time delays and using higher I2C speed.

- sw/cheri/boot/boot_loader.cc
I know we want to minimize spam from the bootloader but this feels like key information. I'm sure I'm not the only one who wonders what bitstream is really loaded in and this could be valuable for external support as well.
> [sw] Report sysinfo hash in bootloader

- sw/cheri/checks/pinmux_all_blocks_check.cc
- sw/cheri/checks/pinmux_check.cc
- sw/cheri/common/platform-pinmux.hh
- sw/cheri/common/platform-pinmux.hh.tpl
- sw/cheri/tests/pinmux_tests.hh
- util/top_gen/generator.py
This PR modifies the Pinmux driver `platform-pinmux.hh` so that it is now automatically generated by `top_gen.py`, i.e. by running `py util/top_gen.py`. This is done using a corresponding template file `sw/cheri/common/platform-pinmux.hh.tpl`. The output of the driver is designed to match the previous output (see changes to `platform-pinmux.hh`), apart from a few key aspects:
- After discussion with @HU90m and @marnovandermaas, I've switched from using driver-specific pin/block names to matching the "doc"/pin names used by `top_gen` already. This minimises the amount of work that this PR is doing and makes it easier to use for development. This could change again in the future when it comes to upstreaming the finalised driver to CHERIoT RTOS to meet coding conventions, but this is being …
> Automatically generate the pinmux driver from `top_config.toml`

- data/top_config.toml
- doc/ip/pinmux/README.md
- rtl/system/pinmux.sv
- sw/cheri/checks/pinmux_all_blocks_check.cc
- sw/cheri/checks/pinmux_checker.cc
- sw/cheri/checks/pinmux_checker.hh
- sw/cheri/common/platform-pinmux.hh
This PR fixes the "all blocks" manual pinmux check (and the pinmux checker in general) so that the latest `main` which includes changes from #262 will now work again. See the commit messages for more details.
This PR primarily does 3 things:
1. Updates the Pinmux config to add the SPI Chip Select to PMOD, where it was previously missing. Whilst at it, I also updated PMOD0 to use SPI2 instead of SPI3, and PMOD1 to use SPI3 instead of SPI4, because it appears that the eventual pinmux mapping (see [here](https://github.com/lowRISC/sonata-system/blob/8df6c195198b7b0121173351391f841b0896a176/doc/ip/pinmux/pin_mappings.svg)) intends to use this mapping. By making this smaller change now in this PR, it reduces the amount of work we have to do later, as the "all blocks" test should stay passing …
> Fix "all blocks" manual pinmux check so it works again after Chip Select added to Pinmux

- dv/dpi/spidpi/spidpi.cc
Driving out the clock to a simulated SPI device without corresponding assertion of CS caused the bit-level handling to get out of step, resulting in a failure to read JEDEC ID from the SPI flash after (in this case) the IRQ testing performs a small number of byte reads with the CS line intentionally deasserted (internal loopback mode).
> Protect SPI DPI model reads against SCK toggling without CS assertion

- rtl/system/sonata_system.sv
The SPI controller does not produce enable signals for the output CS lines, they are a requirement of pinmux. Ensure that all are pulled high, and not just the first.
This would impact other SPI devices as and when they are connected, but prevented operation of the LCD module in #290.
> All SPI CS enables must be pulled high

- rtl/fpga/top_sonata.sv
Pull output pins high when their output isn't enabled. They are pulled high because SPI CS and UART TX lines should default to being pulled high.
> fpga: Change output pins to pull high by default.

- dv/verilator/top_verilator.sv
- rtl/fpga/top_sonata.sv
- rtl/system/sonata_system.sv
Re-express some wiring and ensure that inputs are defined within top_verilator to achieve a better match with the FPGA implementation in top_sonata.
In particular ensure that the output pins are driven high when disabled as per the the FPGA builds, which is important for SPI CS and UART TX lines.
> Improve simulation match with FPGA

- sw/cheri/tests/pinmux_tests.hh
- sw/cheri/tests/spi_tests.hh
See commit messages for more details.
Alongside a couple of code improvements, this PR primarily focuses on the following:
- Make the existing SPI Pinmux test also mux the Flash's CS pin.
- Make the SPI Pinmux test more resilient by resetting the flash after muxing any SPI pins, to recover from erroneous states caused by muxing pins.
- Extend the SPI Pinmux test to specifically check whether muxing of the CS is working. That is, it only disables the CS via pinmux and checks that the test fails, and then re-enables it and checks that it passes again. This is to give confidence that the pinmux surrounding chip selects specifically is working, as this is an area that has undergone a lot of changes recently in the RTL.
This has been tested to pass on FPGA locally; as it only touches the tests …
> Improve Pinmux testing to account for SPI Chip Select

- sw/cheri/common/console.hh
- sw/cheri/common/sonata-devices.hh
- sw/cheri/tests/pinmux_tests.hh
- sw/cheri/tests/usbdev_tests.hh
Addresses some comments from the Pinmux tests PR (#227) after it was merged. This adds in some missing SPI (re)-initialisation logic and does some minor refactoring to make the code cleaner in places. It also makes a minor change formatting the output of the USB test to make it more consistent.
See the comments and discussion on that PR for the reasons for these changes (or omissions of changes). The migration to using the new GPIO driver in `cheriot-rtos` should be done in a separate PR as that is a wider change to the codebase which should be isolated.
The first commit (4d3d1712e7a9e3d93bda4e10c4dfc7d4ce8ebb69) is addressing comments from @HU90m, the second (b6be3bb53b509747728d146d3c6995eec661f1b7) is addressing comments from @engdoreis.
> Address comments from Pinmux Test PR

- data/synth_timing.xdc
Getting tight on timing on some SPI I/O paths, so relax some of the more arbitrary ones to help overall timing pressure.
> Relax timing constraints on some SPI I/O

- sw/cheri/tests/hyperram_tests.hh
- sw/cheri/tests/plic_tests.hh
- sw/cheri/tests/uart_tests.hh
- sw/cheri/tests/usbdev_tests.hh
This PR contains changes to a few tests to make the formatting of the test output more consistent and cohesive. This also makes it easier to identify failures in the PLIC tests by adding explicit coloured `PASS`/`FAIL` messages to the end of each interrupt log. It also adds the ability to modify the number of test iterations for older tests that did not previously support this feature (PLIC and UART). See the commit messages for more details.
This PR primarily changes the output formatting and adds the ability to run multiple iterations; it should not change the functionality of the tests themselves.
> Make test output formatting more consistent

- data/synth_timing.xdc
1. Add constraints for the new PMOD C ports.
2. Update PMOD 0/1 constraints for SPI interface now present (along with I^2C and UART).
3. Relax USB I/O constraints a bit to aid overall timing.
> Update PMOD and USB timing constraints

- rtl/ip/spi/rtl/spi.sv
- rtl/system/sonata_system.sv
With the semantic change to the `SPI_NUM` parameter, the final 3 SPI controllers lost their ability to stimulate the PLIC. Correct the wiring.
(Built into FPGA on top of PR #323 and timing-clean; tests/test_runner passing.)
> Fix SPI controller interrupt routing

- rtl/fpga/top_sonata.sv
This RST pin is an active low reset signal to most mikroBUS Click boards, but some boards use it as an active low Read Enable (RE) pin, so presently not all boards are supported.
Avoid producing undefined behaviour on (hopefully) the majority of boards, and rely upon power-cycling and software-reset mechanisms.
> Ensure mikroBUS Click RST/RE pin is driven

- flake.lock
- nix/software.nix
- sw/cheri/CMakeLists.txt
- sw/cheri/checks/usbdev_check.cc
- sw/cheri/common/usbdev-utils.hh
- sw/cheri/tests/plic_tests.hh
- sw/cheri/tests/usbdev_tests.hh
- Updated to latest version of lowRISC RTOS fork
- Updated lowrisc-nix version
- We'll need the latest version of the compiler to be able to build the
upstream CHERIoT RTOS.
> Updated to latest RTOS fork and lowrisc-nix

- util/sonata-openocd-cfg.tcl
This solves three deprecation warnings when running the memory helper utility script.
> OpenOCD solve deprecation warnings

- sw/cheri/checks/spi_test.cc
SPI controller 2 (now once again through pinmux) drives the application flash; update spi_test to use the correct controller.
Tested and once again producing correct output.
> Application flash has moved; update spi_test

- dv/dpi/spidpi/spi_lcd.cc
- dv/dpi/spidpi/spi_lcd.hh
- sw/cheri/checks/lcd_check.cc
- sw/common/defs.h
- vendor/display_drivers.lock.hjson
- vendor/display_drivers/st7735/lcd_st7735.c
- vendor/display_drivers/st7735/lcd_st7735_cmds.h
Modify the use of GPIO pins to match hardware changes.
The DPI model of the LCD panel now supports all rendering orientations for other tests in simulation.
Modify the lcd_check code to support operation in landscape orientation and not just portait. This was necessary to assist with bring up of other simulation tests; 3 of the possible 8 orientations are in use.
> LCD DPI model and lcd_check updates

- sw/cheri/tests/spi_tests.hh
Courtesy of a request from @alees24. Enables the (already implemented) SPI external loopback test by adding an external jumper cable between pins MB3 and MB4 on the mikroBUS click header. This has been added to the FPGA in CI so that this should pass. Performs appropriate pinmuxing if the SPI test is configured to run this test, so that the test can pass.
> Enable SPI external loopback test between MB3 & MB4

- data/top_config.toml
- doc/ip/pinmux/README.md
- rtl/system/pinmux.sv
Previously both pin 6 and 9 were connected to PWM channel 2
> Connect arduino shield pin 9 to correct PWM channel

- python-requirements.txt
This dependency is necessary for the test runner.
> Python requirement serial should be pyserial

- util/interactive_helpers.tcl
Introduce a new TCL file for helper procedures for use in interactive Vivado sessions. The main addition is a cell highlighting proc useful for viewing where the different parts of the logical design have been placed.
> Add interactive helper file, incl. highlighter

- doc/dev/ref-manual.md
7 MiB of HyperRAM is not accessible yet, so is marked as reserved instead. Also there is now only 128 KiB of SRAM. HyperRAM control and debug module are not available either so these are just marked as reserved for now.
> Memory map updated for v1.0

- data/pins_sonata.xdc
- data/synth_timing.xdc
It appears the `ASYNC_REG` property does not infer timing exceptions. It seem we're lucky at 40 MHz clk_sys that it is possible to meet timing without them, but better to make timing easier where possible. Restore the previous `set_false_path` commands for `prim_flop_2sync`.
> Restore prim_flop_2sync timing exceptions

- flow/vivado_hook_place_design_pre.tcl
- flow/vivado_setup.tcl
- sonata.core
Manually insert delay in the form of BUF (LUT1) cells directly before the lcd_copi output buffer (OBUF) to satisfy the large hold requirement of the LCD driver chip.
If left to add hold-fixing itself, the tool occasionally causes setup timing failures on internal shift/loopback paths by placing the hold-fixing (in the form of a hold detour) too early in the path. Hold fixing as large as this should be put close to the port, after all other paths have branch off. Why the tool decides to insert such large delays so early in the path, I do not know.
> Insert delay on lcd_copi to avoid timing issue

- doc/ip/spi.md
This rewrites the SPI table to include the four chip select wires and what their different functions are.
> SPI host doc updated with chip select

- doc/dev/release-procedure.md
These are some changes that I ran into while doing the v1.0 release.
> Release procedure update

- .gitignore
- sw/cheri/sim_boot_stub/Makefile
- sw/cheri/sim_boot_stub/boot.S
- sw/cheri/sim_boot_stub/boot_sram.S
This boot stub is useful for SRAM only examples like the ones in the current upstream RTOS.
> Simulator boot stub for SRAM added

- doc/guide/sdcard-setup.md
- dv/dpi/spidpi/spi_microsd.cc
- dv/dpi/spidpi/spi_microsd.hh
- dv/dpi/spidpi/spidpi.cc
- dv/verilator/top_verilator.sv
- sonata.core
- sw/cheri/checks/CMakeLists.txt
- sw/cheri/checks/sdraw_check.cc
- sw/cheri/common/console.hh
- sw/cheri/common/filesys-utils.hh
- sw/cheri/common/sdcard-utils.hh
- sw/cheri/tests/lorem_text.hh
- sw/cheri/tests/sdcard_tests.hh
- sw/cheri/tests/test_runner.cc
**CI failures are expected**; there is no microSD card( image) in ~~either~~ simulation~~or FPGA testing~~ at present.
This PR does the following:
Commit 1:
- Introduces SD card support on top of the SPI driver
- Adds a _manual_ 'check' program called 'sdraw_check' that insists upon manual insertion of a card that may be corrupted by the test, and then performs a number of randomised block writes and reads to check that these occur successfully.
Commit 2:
- Introduces Read Only support for a single FAT32 partition (as SD cards are typically shipped by manufacturers).
- Adds SD card testing to the 'test_runner' regression test in CI to test (i) SD card presence, (ii) the ability to read the card properties, (iii) the ability to read a sample text file from the root directory of a FAT32 …
> SD card access and Read Only FAT32 file system support

- sw/cheri/checks/tag_test.S
The test now writes two capabilities to the end of SRAM, one with base zero and one with base at the end of SRAM. After the sweep it checks that the base zero capability's tag stays in tact while the one at the end of SRAM is cleared. Note this is different from the CLC test because the revocation tags are cleared before testing so the CLC will not clear the tags if the hardware revoker hasn't already.
> Revocation control test revocation happens.

- dv/verilator/top_verilator.sv
- sw/cheri/common/sonata-devices.hh
- sw/cheri/tests/pinmux_tests.hh
- sw/cheri/tests/pwm_tests.hh
See the commit messages for more detailed explanations. This PR introduces a new `pinmux_pwm_test` which tests that a PWM instance can be muxed, and that the existing PWM loopback testing works only when the pinmux is configured correctly. If running in CI, this test would be sufficient to catch the issue fixed in #369.
I've tested this on both FPGA and in simulation locally, and the FPGA in CI is already set up with a jumper cable so this test should be passing. I've also added the loopback to the simulation model so this can pass there as well.
> Add Pinmux PWM test

- doc/ip/gpio.md
- doc/ip/pinmux/README.md
Added notes to pinmux and GPIO sections of the manual regarding the impact of the pinmux output selector defaulting on 0b10 and the importance of correctly setting the pinmux before attempting to use the RPi header's GPIO pins as outputs.
> Added notes on using the RPi header for GPIO.

- rtl/ip/rev_ctl/rtl/rev_ctl.sv
This was causing undeclared identifier warnings.
> Revocation control: define done earlier

- doc/dev/simulation.md
The code was tested as part of this PR: https://github.com/CHERIoT-Platform/devcontainer/pull/19
> Simulation documentation: add Docker instructions

- doc/ip/spi.md
Remove sentence on chip selects going through GPIO. Also added the INFO and CS registers.
> SPI doc updated

- sw/cheri/checks/hyperram_test.cc
- sw/cheri/checks/lcd_check.cc
- sw/cheri/checks/pinmux_all_blocks_check.cc
- sw/cheri/checks/pinmux_check.cc
- sw/cheri/checks/pinmux_checker.hh
- sw/cheri/checks/revocation_test.cc
- sw/cheri/checks/rgbled_test.cc
- sw/cheri/checks/rs485_check.cc
- sw/cheri/checks/rs485_spam_check.cc
- sw/cheri/checks/sdraw_check.cc
- sw/cheri/checks/spi_test.cc
- sw/cheri/checks/system_info_check.cc
- sw/cheri/checks/uart_check.cc
- sw/cheri/checks/uart_simexit_check.cc
- sw/cheri/checks/usbdev_check.cc
Move the `[[noreturn]]` attribute to after `extern "C"` when both are used on the one line.
This seems to be required by LLVM 18.
> Move `[[noreturn]]` to after `extern "C"`

- flake.lock
This gives up CHERIoT clang version 19
> nix: updated lowrisc-nix dependency

- rtl/system/autogen/rv_plic/data/rv_plic.hjson
- util/top_gen/generator.py
- vendor/lowrisc_ip/ip_templates/rv_plic/data/rv_plic.hjson.tpl
- vendor/patches/lowrisc_ip/rv_plic/0002-Integrity-Countermeasure-Removed.patch
Previously util/generate_plic.sh would generate an error because the integrity countermeasure was not implemented in the RTL. This removes that countermeasure from the template.
> PLIC: Remove integrity countermeasure for generate

- sw/cheri/sim_boot_stub/boot.S
- sw/cheri/sim_boot_stub/boot_sram.S
This allows it to be written out over the debug module interface.
> Boot stub must end with 4-byte alignment

- README.md
Instead of having to update the latest release link every time, now we just link to the releases page.
> README: release link made generic

- doc/ip/gpio.md
- dv/verilator/top_verilator.sv
- rtl/ip/gpio/gpio.core
- rtl/ip/gpio/rtl/gpio.sv
- rtl/ip/gpio/rtl/gpio_array.sv
- rtl/ip/gpio/rtl/gpio_core.sv
- rtl/ip/gpio/rtl/pcint.sv
- rtl/system/sonata_pkg.sv
- rtl/system/sonata_system.sv
- sw/cheri/checks/CMakeLists.txt
- sw/cheri/checks/pcint_check.cc
- sw/cheri/common/sonata_plic.hh
- sw/cheri/tests/plic_tests.hh
- sw/common/defs.h
Note, waiting on https://github.com/lowRISC/sonata-system/pull/416
This adds the hardware, documentation, and software for GPIO Pin-Change Interrupt logic. This should allow external events to trigger interrupts, albeit in a limited way.
Bitstream utilisation:
| Type | Used | Available | Percentage | Change from 1.2 |
|------|------|-----------|------------|----|
| Slice LUTs | 27,152 | 32,600 | 83.29% | +3.53%pt |
| Slice Registers | 16,540 | 65,200 | 25.37% | +1.24%pt |
| Block RAM Tiles | 41 | 75 | 54.67% | 0%pt |
| DSPs | 13 | 120 | 10.83% | 0%pt |
Compared with: https://github.com/lowRISC/sonata-system/releases/tag/v1.2
Note, part of this increase is from the introduction of the correct synchronisers, perhaps because they cannot be optimised away and in all cases we are specifying …
> Add Pin-Change Interrupts (PCINT) to GPIO

- rtl/system/sonata_system.sv
Switch to the single-cycle multiplier in Ibex by changing the `RV32M` parameter.
Improves multiplication performance while also reducing LUT usage, as much of it can be mapped to the DSP macros in the FPGA.
> Increase multiplier performance

- .github/workflows/ci.yml
Main change is adding a step to the FPGA CI job to print the contents of the Vivado bitstream build logs when the build fails. This should greatly aid debugging (assuming it works).
Also tidied some typos and trailing whitespace in ci.yml while I was in there.
> CI bitstream failure reporting and tidy

- dv/models/fpga/rtl/IOBUF.v
- dv/models/fpga/rtl/ISERDESE2.v
- dv/models/fpga/rtl/OBUF.v
- dv/models/fpga/rtl/ODDR.v
- dv/models/hyperram/rtl/hyperram_W956.sv
- dv/verilator/sonata_system.cc
- dv/verilator/sonata_system_main.cc
- dv/verilator/sonata_verilator_lint.vlt
- dv/verilator/top_verilator.sv
- rtl/system/sonata_system.sv
- sonata.core
- sw/cheri/tests/hyperram_tests.hh
- vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/verilator/simutil_verilator/cpp/verilator_sim_clock.h
- vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.cc
- vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/verilator/simutil_verilator/cpp/verilator_sim_ctrl.h
- vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/verilator/simutil_verilator/simutil_verilator.core
- vendor/patches/lowrisc_ibex/0001-Add-Clock-Support.patch
This PR permits the HyperBus Memory Controller (a.k.a HyperRAM) to be used in simulation with a clocking scheme and timing that much more closely models the HyperRAM activity on the FPGA board. More importantly it makes possible the development and testing in simulation of improved HyperRAM access.
- Modify the simulator control test bench to support multiple clocks of different frequencies and phases; the HBMC requires three different clock signals, having specific phase relationships, and all of a different frequency from the Sonata system clock. This change also permits better modelling of the USB connectivity.
- Introduce build switches `USE_SEPARATED_CLOCKS` and `USE_HYPERRAM_SIM_MODEL` which must be presented to both the C++ test bench and the SystemVerilog design; see …
> HyperRAM clocking scheme, HBMC bring up and W956 simulation model

- dv/verilator/sonata_system.cc
- dv/verilator/top_verilator.sv
- rtl/fpga/clkgen_sonata.sv
- rtl/fpga/top_sonata.sv
- rtl/ip/hyperram/rtl/hbmc_tl_top.sv
- rtl/system/sonata_system.sv
This PR builds on #439 and depends upon it.
Increase the HyperRAM clock frequency to 200MHz.
Adjust the clock frequency to 200MHz as per the W956 datasheet.
The OpenHBMC controller synthesises and operates fine at 200MHz, with the ISERDES operating at 600MHz. Presumably the lower frequency was set conservatively, but now that the HyperRAM interface is capable of bursting and buffering, performance does benefit from the higher frequency.
FPGA builds have been soak testing HyperRAM tests for over 12 hours without encountering any faults.
> Increase HyperRAM clock frequency

- sw/cheri/checks/hyperram_test.cc
Add a new test that both checks and measures the performance of executing a linear sequence of repeated instructions from the HyperRAM.
This is perhaps more relevant for most current uses of the HyperRAM because it is largely intended to be used for additional code rather than loading/storing data.
> Linear execution test of HyperRAM interface

- sonata.core
This just offers explanations of the switches related to the SRAM and the simulation of the HyperRAM. Confession: I confused myself upon returning to this, so I thought it worth clarifying the switches. (Aside: Why, oh why, was `if never introduced with SystemVerilog?)
> Improve the descriptions of the HyperRAM switches
