- flake.lock
- flake.nix
```
nix develop
nix build .#sonata_simulator
```
> Nix Environment and Simulator Build

- data/pins_sonata.xdc
- rtl/fpga/clkgen_sonata.sv
- rtl/fpga/rst_ctrl.sv
- rtl/fpga/top_sonata.sv
- sonata.core
These are mostly ported over from the demo system:
https://github.com/lowRISC/ibex-demo-system/pull/96
> Reset changes

- data/pins_sonata.xdc
- dv/verilator/top_verilator.sv
- rtl/fpga/top_sonata.sv
- rtl/fpga/ws281x_drv.sv
- rtl/system/sonata_system.sv
- sonata.core
- sw/cpp/cheri_sanity/boot.S
- sw/cpp/cheri_sanity/boot.cc
- sw/cpp/error_leds/.gitignore
- sw/cpp/error_leds/Makefile
- sw/cpp/error_leds/README.md
- sw/cpp/error_leds/end.S
- sw/cpp/error_leds/error.S
- sw/cpp/error_leds/irom.ldscript
- vendor/lowrisc_ibex.lock.hjson
- vendor/lowrisc_ibex/rtl/ibex_core.sv
- vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv
- vendor/lowrisc_ibex/rtl/ibex_lockstep.sv
- vendor/lowrisc_ibex/rtl/ibexc_top.sv
- vendor/lowrisc_ibex/rtl/ibexc_top_tracing.sv
This PR adds the CHERI LED error demo to the Sonata repository, as well as actively turn off the RGB LEDs and cleaning up the boot test.
It relies on some changes to the CHERIoT Ibex: https://github.com/lowRISC/cheriot-ibex/commit/e343b23f836761c4aee0f9171c42636e0421fe62
> CHERI error demo

- flake.nix
I hadn't realised but I broke the reproducible sim build in an earlier PR
> Reproducible sim build fix

- data/pins_sonata.xdc
- dv/verilator/top_verilator.sv
- rtl/system/sonata_system.sv
- rtl/system/sram.sv
Some minor changes that I noticed while working on integrating the debug module.
> Minor source code changes

- README.md
> Update docs with note about hackathon image

- dv/verilator/top_verilator.sv
Resolves: https://github.com/lowRISC/sonata-system/pull/46#discussion_r1580900653
> Tie user JTAG to zero for simulation

- rtl/system/sonata_system.sv
Update: Two separate commits to permit builds with and without the switch; combine them and build/merge if happy, please.
This PR introduces an extended reset assertion to hold the core in reset whilst the debugger is downloading code. ~~It is a draft at present because there is a DIP switch that selects between the new behaviour (SW7 in the OFF position) and the previous brief reset assertion (SW7 in the ON position).~~
**Apply the following change** in sdk/core/loader/debug.hh:
```
--- a/sdk/core/loader/debug.hh
+++ b/sdk/core/loader/debug.hh
@@ -393,12 +393,14 @@ namespace
if constexpr (Enabled)
{
// Ensure that the compiler does not reorder messages.
+/*
asm volatile("" ::: "memory");
writer.format("\x1b[35mloader\033[0m");
writer.format(": ");
writer.format(fmt, args...);
- …
```
> Extended reset assertion

- sw/cheri/CMakeLists.txt
- sw/cheri/tests/CMakeLists.txt
- sw/cheri/tests/gpio_check.cc
- sw/cheri/tests/uart_check.cc
- sw/common/defs.h
> Moved UART check over to upstream driver

- sw/cheri/CMakeLists.txt
- sw/cheri/cheriot_toolchain.cmake
- sw/cheri/common/flash-utils.hh
- sw/cheri/common/uart-utils.hh
- sw/cheri/tests/spi_test.cc
- sw/common/defs.h
Moving to our CHERIoT RTOS fork. The goal is to close any divergences between our fork and upstream as soon as possible.
> Moved SPI test over to upstream driver

- doc/dev/fpga-development.md
Closes: https://github.com/lowRISC/sonata-system/issues/88
> Fix link to software build instructions

- doc/guide/fpga-update.md
This adds the XADC read-out for checking power stability if required
> DOC: Add notes about XADC read-out via OpenFPGALoader

- doc/dev/simulation.md
Follow up from: https://github.com/lowRISC/sonata-system/pull/102
> Add documentation for using stub in simulation

- data/pins_sonata.xdc
- data/xbar_main.hjson
- doc/dev/ref-manual.md
- doc/ip/gpio.md
- dv/verilator/top_verilator.sv
- rtl/bus/tl_main_pkg.sv
- rtl/bus/xbar_main.sv
- rtl/fpga/top_sonata.sv
- rtl/system/gpio.sv
- rtl/system/sonata_system.sv
This includes R-Pi HAT, Arduino Shield, mikroBUS Click and PMOD.
> Connect up rest of the header pins

- data/pins_sonata.xdc
- data/xbar_main.hjson
- doc/dev/ref-manual.md
- dv/verilator/top_verilator.sv
- rtl/bus/tl_main_pkg.sv
- rtl/bus/xbar_main.sv
- rtl/fpga/top_sonata.sv
- rtl/system/sonata_system.sv
This reverts commit 4fb79046e6acc2ddd257aa57ea4cdb8e381045e0.
This is based on unresolved comments on PR: https://github.com/lowRISC/sonata-system/pull/112
> Revert "Connect up remaining header pins"

- doc/guide/building-examples.md
> Add UART inspection instruction

- SUMMARY.md
- doc/dev/fpga-development.md
- doc/dev/toolchain-setup.md
- doc/guide/building-examples.md
- doc/guide/fpga-update.md
- doc/guide/getting-started.md
- doc/guide/rp2040-update.md
Various tweaks just to ensure people checking out the new release don't get confused with old examples/flows (e.g. we don't want them to care about building their own toolchain or building any of the software in sonata-system)
> [doc] Updates to reflect current recommended setup and flows

- doc/guide/building-examples.md
Termite was recommended by Colin.
> Mention Termite for serial under Windows

- doc/ip/plic.md
Closes https://github.com/lowRISC/sonata-system/issues/5
> Add list of interrupts to PLIC documentation

- flake.lock
This brings in the new standard doc file filter, which include JPEGs.
> Updated nix lock

- data/pins_sonata.xdc
- data/xbar_main.hjson
- doc/dev/ref-manual.md
- dv/verilator/top_verilator.sv
- rtl/bus/tl_main_pkg.sv
- rtl/bus/xbar_main.sv
- rtl/fpga/top_sonata.sv
- rtl/system/sonata_system.sv
This is a second attempt at this PR: https://github.com/lowRISC/sonata-system/pull/112
There is some feedback on that PR which I have mostly resolved.
The second commit is just formatting, which you can skip during reviewing.
> Connect header GPIOs

- doc/ip/plic.md
Resolves: https://github.com/lowRISC/sonata-system/pull/120#discussion_r1629379762
> Update ethernet interrupt description

- dv/verilator/top_verilator.sv
Report the first occurrence of each CHERI violation on stderr and ensure that this is promptly visible, as a development aid and to help catch the execution of legacy software on CHERI- enabled hardware.
This has been tested in Verilator simulation by running a legacy app which reports a 'Tag' violation at time 0, and with the `error_leds` application which manually triggers (almost) all of the violations; 'Permit Store Local Cap' seems no longer to exist.
> Report CHERI violations on stderr

- sw/cheri/tests/hyperram_tests.hh
The hyperram test check fix only checked the result of the last test, and not each individual test. As a result, the hyperram test would only fail on CI if the last test specifically failed.
I've opted to track test failure via a separate Boolean variable rather than incrementing the `failures` variable each test, so that we retain per-test failure granularity, as otherwise failures would cascade through tests and provide less useful information in CI.
Also fixes a typo.
> Check results of all hyperram tests, and not just the last one

- poetry.lock
- pyproject.toml
The `pkg_resources` module is required by
`vendor/lowrisc_ip/util/tlgen/generate.py`.
> Add setuptools to the python dependencies

- SUMMARY.md
- doc/architecture/sonata-hardware.md
- doc/dev/ref-manual.md
- doc/guide/README.md
- doc/guide/building-examples.md
- doc/guide/updating-system.md
Create some doc/ pages to fill gaps in the documentation tree. Also tweak some of the nearby docs.
> Create pages to fill gaps in doc structure

- rtl/system/gpio.sv
@AlexJones0 can you test whether this works for you?
> GPIO output enable now readable

- SUMMARY.md
You can test this commit using `mdbook serve`.
> Mdbook: add system info to summary

- .github/workflows/ci.yml
- doc/dev/fpga-development.md
- doc/dev/fpga-programming.md
- doc/dev/sw-programming.md
- flake.lock
- flake.nix
- nix/bitstream.nix
- nix/lint.nix
- nix/tests.nix
This PR adds the FPGA test to the repo using the FPGA runner setup by @nbdd0121.
> [CI] Add FPGA runner

- .github/workflows/ci.yml
- doc/dev/fpga-development.md
- flake.nix
- nix/bitstream.nix
- nix/software.nix
- sw/cheri/boot/CMakeLists.txt
Also there are many more little changes. Do read the git commit messages.
> Make bitstream build a little more reproducible

- SUMMARY.md
- doc/dev/release-procedure.md
This adds a document with our release procedure.
> Release procedure documented

- flake.nix
- nix/bitstream.nix
This isn't expected to be the final solution.
> Added fpga dependancies fileset for use by cache

- doc/dev/toolchain-setup.md
- python-requirements.txt
Fixing up two lingering documentation issues.
Closes: https://github.com/lowRISC/sonata-system/issues/124
Closes: https://github.com/lowRISC/sonata-system/issues/97
> Doc update to close some old issues

- dv/verilator/top_verilator.sv
Loopback functionality for SPI, GPIO and UART connections so that the FPGA tests will operate in Verilator simulation too.
Delete a legacy TODO comment, now that we actually model more I/O functionality.
> Introduce loopbacks for testing in simulation

- nix/software.nix
- sw/cheri/CMakeLists.txt
- sw/cheri/common/console.hh
- sw/cheri/tests/hyperram_tests.hh
This new version adds <CR> to the `println` function.
> Add <CR> to println function.

- sw/cheri/tests/spi_tests.hh
> SPI IRQ test

- data/synth_timing.xdc
> XDC remove further ah_tmpio16 usage

- data/pins_sonata.xdc
- data/synth_timing.xdc
Some tweaks to address some CDC warnings (and one typo)
> CDC warning reduction

- sw/cheri/tests/pwm_tests.hh
Addresses feedback from @alees24 after #307 was merged.
Makes some small improvements to the PWM tests. First adds an "Always high" PWM test, which checks that the PWM always outputs 1 when the duty cycle is in some configuration greater where it is greater than the period/counter. This acts as an opposite to the "Always Zero" test.
Second, this PR adds a couple more PWM loopback tests cases, to better cover the range of duty cycles above 50%, which were previously not being tested. These are 224/255 and 192/255.
Third, corrects a couple of typos.
This has been tested to pass on FPGA and CI locally.
> Add PWM Always High test & Misc. Improvements

- sw/cheri/tests/plic_tests.hh
This PR makes sure that the `irq_fired` attribute is correctly reset to `false` after each `wfi()` call in a test, which was previously causing the test to pass even when the interrupt lines for a block were not correctly hooked up in hardware.
As that would cause the entire test runner to halt, this commit then replaces the ASM `wfi` functionality with a basic timeout for handling a fired interrupt, which is set to 10 microseconds by default so as to not cause lengthy waits when running in simulation. This timeout means that the `wfi` function can actually terminate without an interrupt being fired, and that the tests can now query the `irq_fired` attribute to determine whether the test passed or failed, and log accordingly.
When tested locally against a bitstream built on …
> Make PLIC test fail when interrupt not fired

- doc/ip/ram.md
HyperRAM controller was not implemented as documented. Updated the documentation to make it more accurate.
> HyperRAM docs updated

- book.toml
- doc/ip/spi.md
- flake.lock
- flake.nix
Mainly porting things across from Sonata software:
- https://github.com/lowRISC/sonata-software/blob/main/flake.nix
- https://github.com/lowRISC/sonata-software/blob/main/book.toml
> mdBook readme links

- README.md
Updating the sonata-system documentation to point to 1.0
> Update README.md to point to v1.0 Sonata release

- README.md
- doc/guide/fpga-update.md
- doc/guide/rp2040-update.md
- doc/guide/updating-system.md
Some minor doc updates based on a read-through of the earlier pages.
> Doc updates (minor)

- flake.lock
- flake.nix
- nix/software.nix
- sw/cheri/CMakeLists.txt
- sw/cheri/checks/lcd_check.cc
- sw/cheri/checks/pinmux_checker.cc
- sw/cheri/checks/spi_test.cc
- sw/cheri/checks/usbdev_check.cc
- sw/cheri/common/block_tests.cc
- sw/cheri/common/block_tests.hh
- sw/cheri/common/flash-utils.hh
- sw/cheri/common/sdcard-utils.hh
- sw/cheri/common/sonata-devices.hh
- sw/cheri/common/usbdev-utils.hh
- sw/cheri/tests/pinmux_tests.hh
- sw/cheri/tests/plic_tests.hh
- sw/cheri/tests/pwm_tests.hh
- sw/cheri/tests/spi_tests.hh
- sw/cheri/tests/usbdev_tests.hh
I've tried to keep the changes minimal, so the software doesn't make the best use of the new API
> Move onto upstream CHERIoT RTOS

- sw/legacy/link.ld
- sw/legacy/test/memory_test.c
Fix the sram size in linker script for Legacy mode.
> [Legacy] Fix the sram size in linker script

- flake.nix
- nix/software.nix
- nix/tests.nix
- sw/legacy/demo/ethernet/CMakeLists.txt
- sw/legacy/demo/hello_usb/CMakeLists.txt
- sw/legacy/demo/hello_world/CMakeLists.txt
- sw/legacy/demo/i2c_hat_id/CMakeLists.txt
- sw/legacy/demo/lcd_st7735/CMakeLists.txt
- sw/legacy/test/CMakeLists.txt
- sw/legacy/test/memory_test.c
- sw/legacy/timer_test/CMakeLists.txt
- util/test_runner.py
This will hopefuly prevent the legacy sw stack from breaking.
> Run a legacy test to CI

- doc/dev/release-procedure.md
Revision of the release procedure in preparation of v1.2.
> Release revision

- doc/dev/release-procedure.md
Further updates to the release procedure as I was doing the v1.2 release.
> Release procedure further revision

- rtl/ip/gpio/rtl/gpio_core.sv
Something resembling a two stage synchroniser was being used in `gpio_core.sv`, but better to use the matching primitive instead.
> Replace GPIO synchronisers w/canonical primitive
